# NumPy


### Angi is a bingus

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (2911301208.py, line 4)

In [7]:
%pip install numpy

import numpy as np
print(np.__version__)

arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

arr_from_tuple = np.array(('a', 'b', 'c'))
print(arr_from_tuple)
print(type(arr_from_tuple))

Note: you may need to restart the kernel to use updated packages.
2.4.1
[1 2 3 4]
<class 'numpy.ndarray'>
['a' 'b' 'c']
<class 'numpy.ndarray'>



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


## Array Dimensions

In [6]:

# -------------------------
# 0D array (Scalar)
# -------------------------
# A single value with no dimensions
arr_0d = np.array(10)
print(arr_0d)
print("Dimensions:", arr_0d.ndim)

# -------------------------
# 1D array (Vector)
# -------------------------
# A classic one-dimensional array made of scalar values
arr_1d = np.array([1, 2, 3, 4])
print(arr_1d)
print("Dimensions:", arr_1d.ndim)

# -------------------------
# 2D array (Matrix)
# -------------------------
# An array made of 1D arrays (rows and columns)
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr_2d)
print("Dimensions:", arr_2d.ndim)

# -------------------------
# 3D array (Tensor)
# -------------------------
# An array made of 2D arrays
arr_3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
])
print(arr_3d)
print("Dimensions:", arr_3d.ndim)

# -------------------------
# Higher-dimensional array
# -------------------------
# Force a minimum of 10 dimensions
more_dimensions = np.array([1, 2, 3], ndmin=10)
print(more_dimensions)
print("Dimensions:", more_dimensions.ndim)




10
Dimensions: 0
[1 2 3 4]
Dimensions: 1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensions: 2
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimensions: 3
[[[[[[[[[[1 2 3]]]]]]]]]]
Dimensions: 10


## Building arrays

## Looking at the Shape of an Array

NumPy arrays have a shape, which describes the number of dimensions and the size of each dimension.

(2, 3, 3) → 2 layers, each with 3 rows and 3 columns

In other words:
- There are 2 two-dimensional arrays
- Each 2D array contains 3 one-dimensional arrays (rows)
- Each 1D array contains 3 zero-dimensional values (scalars)

## Your Turn

Create a NumPy array containing 10 elements. Practice reshaping it into as many different valid shapes as possible.


## Array indexing 

## Slicing

## Your turn: 
Slice this from the array below this
 [[ 1,  3],
  [ 7,  9]]

# Looping through arrays
NumPy has tools that reduce the need for loops, but let’s take a look at how this works in vanilla Python.

Lets make it easier

## Joining Arrays


## Splitting arrays

## Where 
Who needs loops when you have where

## Your Turn

Given the array below, use np.where() to find the indices of all values that are between 0.3 and 0.7 (inclusive).
arr = np.array([0.15, 0.32, 0.58, 0.71, 0.44, 0.89, 0.67])
Hint you can use the '&' operator 


## Comparing 

## Boolean Indexing
Boolean indexing can simplify data for ML models.

## Conditions 


## Math
- mean
- sum - total
- cumsum - sum as we go